---
- hosts: localhost
  connection: local
  become: true
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

  pre_tasks:
  - name: Creatig temp folder
    tags: always
    ansible.builtin.file:
      path: /home/{{ invoking_user }}/.tmp
      state: directory
      mode: '0777'

  - name: Update all packages (Debian based)
    tags: always
    ansible.builtin.apt:
      update_cache: yes
      upgrade: dist
    when: ansible_os_family == "Debian"

  - name: Update all packages (Fedora based)
    tags: always
    ansible.builtin.dnf:
      update_cache: yes
      update_only: yes
    when: ansible_os_family == "RedHat"

- hosts: all
  become: true

  tasks:
    - name: Basic Setup
      tags: always
      import_role:
        name: basic_setup

- hosts: all
  become: true

  tasks:
    - name: Workstation setup
      tags: workstations
      import_role:
        name: workstations_setup
      when: inventory_hostname in groups["workstations"]
