---
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
  - name: Importing Variables
    ansible.builtin.include_vars: globalVars.yml
#      - "{{ ansible_os_family }}.yml"

  - name: Creatig temp folder
    tags: always
    ansible.builtin.file:
      path: /home/{{ invoking_user }}/.tmp
      state: directory
      mode: '0777'

- hosts: all
  become: true
  tags: always
  gather_facts: no
  roles:
    - role: robertdebock.rpmfusion

- hosts: all
  become: true
  tags: always
  tasks:
    - name: Basic Setup
      tags: always
      import_role:
        name: basic_setup

- hosts: all
  become: true
  tasks:
    - name: Workstation setup
      tags: workstations
      import_role:
        name: workstations_setup
      when: inventory_hostname in groups["workstations"]

#- hosts: jsproart
#  become: true
#  tasks:
#    - name: JSProArt Laptop Setup
#      import_role:
#        name: proart_setup
