---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
  - name: Importing Variables
    ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

  - name: Creatig temp folder
    tags: always
    ansible.builtin.file:
      path: /home/{{ invoking_user }}/.tmp
      state: directory
      mode: '0777'

  - name: Enabling Contrib (Based)
    ansible.builtin.lineinfile:
      path: /etc/apt/sources.list
      backup: true
      search_string: deb http://deb.debian.org/debian bookworm main non-free-firmware
      line: deb http://deb.debian.org/debian/ bookworm main contrib non-free
      owner: root
      group: root
      mode: '0644'
    when: ansible_distribution == "Debian"

  - name: Update all packages (Debian based)
    tags: always
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: Update all packages (Fedora based)
    tags: always
    ansible.builtin.dnf:
      name: "*"
      update_only: yes
      update_cache: yes
      state: latest
    when: ansible_os_family == "RedHat"

- hosts: all
  become: true

  tasks:
    - name: Basic Setup
      tags: always
      import_role:
        name: basic_setup

- hosts: all
  become: true

  tasks:
    - name: Workstation setup
      tags: workstations
      import_role:
        name: workstations_setup
      when: inventory_hostname in groups["workstations"]
