- name: Installing Laptop Apps
  ansible.builtin.package:
    state: latest
    name:
      - fakeroot
      - gamemode
      - gnome-tweaks
      - gparted
      - gparted
      - psutils
      - python3-psutil
      - remmina
      - syncthing
      - vlc
      - wine
      - winetricks

- name: Installing Handbrake from Flathub
  community.general.flatpak:
    name: fr.handbrake.ghb
    state: present
  when: ansible_os_family == "RedHat"

- name: Installing Jellyfin client
  community.general.flatpak:
    name: com.github.iwalton3.jellyfin-media-player
    state: present
