- name: Installing Laptop Apps
  ansible.builtin.package:
    state: latest
    name:
      - btop
      - fakeroot
      - gnome-tweaks
      - gparted
      - psutils
      - python3-psutil
      - syncthing
      - vlc
      - python3-vlc
      - wine
      - winetricks
      - asunder
#      - keeperpasswordmanager
#      - gamemode
#      - remmina

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Installing Handbrake from Flathub
  community.general.flatpak:
    name: fr.handbrake.ghb
    state: present
    remote: flathub
  when: ansible_os_family == "RedHat"

- name: Installing Jellyfin client
  community.general.flatpak:
    name: com.github.iwalton3.jellyfin-media-player
    remote: flathub
    state: present
