- name: Installing Laptop Apps
  ansible.builtin.package:
    state: latest
    name:
      - putty
      - gtkterm
      - vlc
      - wine
      - gparted
      - syncthing
#      - neofetch

- name: Installing PSUtils
  ansible.builtin.package:
    state: latest
    name:
      - psutils
      - python3-psutil
  #when: ansible_os_family == "RedHat"

- name: Installing Handbrake from Flathub
  community.general.flatpak:
    name: fr.handbrake.ghb
    state: present
  when: ansible_os_family == "RedHat"
