- name: Installing Virtualbox (Debian Based)
  ansible.builtin.package:
    state: latest
    name:
      - virtualbox
      - virtualbox-dkms
#      - virtualbox-ext-pack
      - virtualbox-guest-additions-iso
  when: ansible_os_family == "Debian"

- name: Importing VirtualBox Key (Fedora Based OS)
  ansible.builtin.rpm_key:
    key: https://www.virtualbox.org/download/oracle_vbox_2016.asc
  when: ansible_os_family == "RedHat"

- name: Adding VirtualBox Repo (Fedora Based OS)
  ansible.builtin.yum_repository:
    name: virtualbox
    description: Fedora $releasever - $basearch - VirtualBox
    baseurl: http://download.virtualbox.org/virtualbox/rpm/fedora/$releasever/$basearch
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: true
    gpgkey: https://www.virtualbox.org/download/oracle_vbox_2016.asc
  when: ansible_os_family == "RedHat"

- name: Installing VirtualBox (Fedora Based)
  ansible.builtin.package:
    name:
      - kernel-devel
      - akmod-VirtualBox
      - VirtualBox
    state: latest
  when: ansible_os_family == "RedHat"

- name: Checking First Run
  tags: always
  stat:
    path: /home/{{ invoking_user }}/.firstRun
  register: result

- name: Reboot if this is the first time running the playbook
  tags: always
  import_role:
    name: reboot_device
  when: not result.stat.exists

- name: Restart Service (Fedora Based)
  ansible.builtin.service:
    name: vboxdrv
    state: restarted
  when: ansible_os_family == "RedHat"

- name: Capturing VirtualBox Edition
  ansible.builtin.shell: vboxmanage --version
  register:  VBResults
- debug:
    msg: "{{ VBResults.stdout[:6] }}"
  ignore_errors: true

- name: Downloading VirtualBox Extension Pack
  ansible.builtin.get_url:
    url: https://download.virtualbox.org/virtualbox/{{ VBResults.stdout[:6] }}/Oracle_VM_VirtualBox_Extension_Pack-{{ VBResults.stdout[:6]  }}.vbox-extpack
    dest: /home/jpatr/.tmp//Oracle_VM_VirtualBox_Extension_Pack-{{ VBResults.stdout[:6]  }}.vbox-extpack
    mode: '0777'

  #Thanks to the VBox forum for the echo trick (https://forums.virtualbox.org/viewtopic.php?p=427956#p427956)
- name: Installing Extensions
  ansible.builtin.shell:
    cmd: echo y | VBoxManage extpack install --replace Oracle_VM_VirtualBox_Extension_Pack-{{ VBResults.stdout[:6]  }}.vbox-extpack
    chdir: /home/jpatr/.tmp/

- name: Cleaning Temp File
  ansible.builtin.file:
    path: /home/jpatr/.tmp//Oracle_VM_VirtualBox_Extension_Pack-{{ VBResults.stdout[:6]  }}.vbox-extpack
    state: absent

- name: Adding user to vboxusers group.
  ansible.builtin.user:
    name: jpatr
    groups: vboxusers
    append: yes
