- name: Installing Kernel Stub (Pop_OS! only)
  ansible.builtin.package:
    state: latest
    name:
      - build-dep
      - kernelstub
  when: ansible_distribution == "Pop!_OS"

- name: Enabling Virtualization at Boot (Pop_OS! only / AMD CPU)
  ansible.builtin.command:
    cmd: kernelstub --add-options "amd_iommu=on"
  when:
    - ansible_distribution == "Pop!_OS"
    - ansible_processor[0] == "AuthenticAMD"
#  when: ansible_distribution == "Pop!_OS"
#  when: ansible_processor[0] == "AuthenticAMD"

- name: Enabling Virtualization at Boot (Pop_OS! only / Intel CPU)
  ansible.builtin.command:
    cmd: kernelstub --add-options "intel_iommu=on"
  when:
    - ansible_distribution == "Pop!_OS"
    - ansible_processor[0] == "AuthenticAMD"
#  when: ansible_distribution == "Pop!_OS"
#  when: ansible_processor[0] == "AuthenticAMD"
