- name: Installing Kernel Stub (Pop_OS! only)
  ansible.builtin.package:
    state: latest
    name:
      - build-dep
      - kernelstub
  when: ansible_distribution == "Pop!_OS"

- name: Enabling Virtualization at Boot (Pop_OS! only / AMD CPU)
  ansible.builtin.command:
    cmd: kernelstub --add-options "amd_iommu=on"
  when: (ansible_distribution == "Pop!_OS") and (ansible_processor == "AuthenticAMD")

- name: Enabling Virtualization at Boot (Pop_OS! only / Intel CPU)
  ansible.builtin.command:
    cmd: kernelstub --add-options "intel_iommu=on"
  when: (ansible_distribution == "Pop!_OS") and (ansible_processor == "GenuineIntel")

- name: Enabling Virtualization at Boot (Grub based / AMD CPU)
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    backup: true
    search_string: quiet"
    line: quiet amd_iommu=on"
    owner: root
    group: root
    mode: '0644'
  when:
    - not ansible_distribution == "Pop!_OS"
    - ansible_processor == "AuthenticAMD"
#  when: (not ansible_distribution == "Pop!_OS") and (ansible_processor == "AuthenticAMD")

- name: Enabling Virtualization at Boot (Grub based / Intel CPU)
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    backup: true
    search_string: quiet"
    line: quiet intel_iommu=on"
    owner: root
    group: root
    mode: '0644'
  when:
    - not ansible_distribution == "Pop!_OS"
    - ansible_processor == "GenuineIntel")
#  when: (not ansible_distribution == "Pop!_OS") and (ansible_processor == "GenuineIntel")

- name: Updating Grub (If Needed)
  ansible.builtin.command:
    cmd: grub-mkconfig -o /boot/grub2/grub.cfg
  when:
    - not ansible_distribution == "Pop!_OS"

