- name: Installing Kernel Stub (Pop_OS! only)
  ansible.builtin.package:
    state: latest
    name:
      - kernelstub
  when:
    - ansible_distribution == "Pop!_OS"

- name: Enabling Virtualization at Boot (Pop_OS! only / AMD CPU)
  ansible.builtin.command:
    cmd: kernelstub --add-options "amd_iommu=on"
  when:
    - ansible_distribution == "Pop!_OS"
    - ansible_processor == "AuthenticAMD"

- name: Enabling Virtualization at Boot (Pop_OS! only / Intel CPU)
  ansible.builtin.command:
    cmd: kernelstub --add-options "intel_iommu=on"
  when:
    - ansible_distribution == "Pop!_OS"
    - ansible_processor == "GenuineIntel"

- name: Enabling Virtualization at Boot (Grub based / AMD CPU)
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    backup: true
    search_string: GRUB_CMDLINE_LINUX="rhgb quiet"
    line: GRUB_CMDLINE_LINUX="rhgb quiet amd_iommu=on"
    owner: root
    group: root
    mode: '0644'
  when:
    - ansible_distribution != "Pop!_OS"
    - ansible_processor[1] == "AuthenticAMD"

- name: Enabling Virtualization at Boot (Grub based / Intel CPU)
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    backup: true
    search_string: GRUB_CMDLINE_LINUX="rhgb quiet"
    line: GRUB_CMDLINE_LINUX="rhgb quiet intel_iommu=on"
    owner: root
    group: root
    mode: '0644'
  when:
    - ansible_distribution != "Pop!_OS"
    - ansible_processor[1] == "GenuineIntel"

- name: Updating Grub (Fedora Based)
  ansible.builtin.command:
    cmd: grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg
  when:
    - ansible_os_family == "RedHat"

- name: Updating Grub (Fedora Debia)
  ansible.builtin.command:
    cmd: update-grub
  when:
    - ansible_os_family == "Debian"
    - ansible_distribution != "Pop!_OS"
