- name: Installing Kernel Stub (Pop_OS! only)
  ansible.builtin.package:
    state: latest
    name:
      - build-dep
      - kernelstub

- name: Enabling Virtualization at Boot (Pop_OS! only / AMD CPU)
  ansible.builtin.commmand: kernelstub --add-options "amd_iommu=on"
  when: ansible_processor[0] == "AuthenticAMD"

- name: Enabling Virtualization at Boot (Pop_OS! only / Intel CPU)
  ansible.builtin.commmand: kernelstub --add-options "intel_iommu=on"
  when: ansible_processor[0] == "GenuineIntel"
