- name: Uninstalling default Libreoffice
  ansible.builtin.package:
    state: absent
    name:
      - libreoffice*

- name: Installing Libreoffice from Flathub
  community.general.flatpak:
    name: org.libreoffice.LibreOffice
    state: latest
