- name: Uninstalling default Libreoffice (Debian Based)
  ansible.builtin.package:
    state: absent
    name:
      - libreoffice*
  when: ansible_os_family == "Debian"

- name: Uninstalling default LibreOffice (Fedora Based)
  ansible.builtin.dnf:
    name: '@libreoffice'
    state: absent
  when: ansible_os_family == "RedHat"

- name: Installing Libreoffice from Flathub
  community.general.flatpak:
    name: org.libreoffice.LibreOffice
    state: present
