- name: Installing Flatpack Apps
  community.general.flatpak:
    name:
      - org.gnome.Extensions
      - com.jgraph.drawio.desktop
      - fr.handbrake.ghb
      - org.onlyoffice.desktopeditors
      - com.protonvpn.www
      - com.heroicgameslauncher.hgl
    state: present
