- name: Installing Flatpack Apps
  community.general.flatpak:
    name:
      - org.gnome.Extensions
      - io.github.ungoogled_software.ungoogled_chromium
      - com.jgraph.drawio.desktop
      - com.heroicgameslauncher.hgl
      - net.davidotek.pupgui2
      - fr.handbrake.ghb
      - org.onlyoffice.desktopeditors
    state: present
