- name: Installing Flatpack Apps
  community.general.flatpak:
    name:
      - org.gnome.Extensions
      - com.jgraph.drawio.desktop
      - fr.handbrake.ghb
      - org.onlyoffice.desktopeditors
      - com.protonvpn.www
      - com.heroicgameslauncher.hgl
#      - io.github.ungoogled_software.ungoogled_chromium
#      - net.davidotek.pupgui2
    state: present
