basic_setup_amd_microcode_package: linux-firmware
basic_setup_lm_sensors_package: lm_sensors
basic_setup_nfs_client_package: nfs-utils
basic_setup_openssh_service: ssh
basic_setup_py_psutils: python-psutil
