# I straight up stole/modified task this from Jay LaCroix at learnlinux.tv
# https://github.com/LearnLinuxTV/personal_ansible_desktop_configs/blob/main/roles/base/tasks/system_setup/microcode.yml

- name: System Setup | Microcode | Install Package for AMD
  tags: always
  ansible.builtin.package:
    name: "{{ amd_microcode_package }}"
    state: present
  when:
    - ansible_facts['processor'] == "AuthenticAMD"

- name: System Setup | Microcode | Install Package for Intel
  tags: always
  ansible.builtin.package:
    name: "{{ intel_microcode_package }}"
    state: present
  when:
    - ansible_facts['processor'] == "GenuineIntel"
    - ansible_facts['os_family'] == "Debian"
