- name: Install Common Apps
  tags: always
  ansible.builtin.package:
    state: present
    name:
      - tmux
      - wget
      - curl

- name: Install Build Essentials (Debian Based)
  tags: always
  ansible.builtin.apt:
    state: present
    name: build-essential
  when: ansible_facts['os_family'] == "Debian"

- name: Install Build Essentials (Fedora Based)
  tags: always
  ansible.builtin.dnf:
    name:
      - '@development-tools'
      - automake
      - gcc
      - gcc-c++
      - kernel-devel
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Install Media Plugins (Fedora)
  ansible.builtin.dnf:
    name:
      - '@multimedia'
#      - ffmpeg-free
#      - ffmpeg
    allowerasing: true
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Install Hardware Media Codecs (AMD CPU Fedora)
  ansible.builtin.dnf:
    name:
      - mesa-va-drivers-freeworld
    state: present
  when:
    - ansible_facts['processor'] == "AuthenticAMD"
    - ansible_facts['os_family'] == "RedHat"

- name: Install Hardware Media Codecs (Intel CPU Fedora)
  ansible.builtin.dnf:
    name:
      - intel-media-driver
  when:
    - ansible_facts['processor'] == "GenuineIntel"
    - ansible_facts['os_family'] == "RedHat"

- name: Check for NVIDIA GPU
  ansible.builtin.shell: lspci | grep -i nvidia
  register: nvidia_check
  ignore_errors: true
  changed_when: false

- name: Run task only if NVIDIA GPU is present
  ansible.builtin.debug:
    msg: "NVIDIA GPU detected, proceeding with installation..."
  when: nvidia_check.rc == 0

- name: Install Hardware Media Drivers and Codecs (NVIDA GPU Fedora)
  ansible.builtin.dnf:
    name:
      - libva-nvidia-driver
      - xorg-x11-drv-nvidia-cuda
      - xorg-x11-drv-nvidia-cuda-libs
      - nvtop
  when:
    - ansible_facts['os_family'] == "RedHat"

- name: Enabling NVidia Hibernate Service
  ansible.builtin.systemd_service:
    name: nvidia-hibernate.service
    enabled: true
  when: ansible_facts['os_family'] == "RedHat"

- name: Enabling NVidia Suspend Service
  ansible.builtin.systemd_service:
    name: nvidia-suspend.service
    enabled: true
  when: ansible_facts['os_family'] == "RedHat"

- name: Enabling NVidia Resume Service
  ansible.builtin.systemd_service:
    name: nvidia-resume.service
    enabled: true
  when: ansible_facts['os_family'] == "RedHat"

- name: Enabling NVidia Power Service
  ansible.builtin.systemd_service:
    name: nvidia-powerd.service
    enabled: true
  when: ansible_facts['os_family'] == "RedHat"
