- name: Install Common Apps
  tags: always
  ansible.builtin.package:
    state: latest
    name:
      - colordiff
      - tmux
      - wget
      - curl

- name: Install Build Essentials (Debian Based)
  tags: always
  ansible.builtin.apt:
    state: latest
    name: build-essential
  when: ansible_os_family == "Debian"

- name: Install Build Essentials (Fedora Based)
  tags: always
  ansible.builtin.dnf:
    name:
      - '@Development tools'
      - '@Development Libraries'
  when: ansible_os_family == "RedHat"
