- ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Enabling Contrib (Based)
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    backup: true
    search_string: deb http://deb.debian.org/debian/ bookworm main non-free
    line: deb http://deb.debian.org/debian/ bookworm main contrib non-free
    owner: root
    group: root
    mode: '0644'
  when: ansible_distribution == "Debian"

- block:
  - ansible.builtin.import_tasks: subtasks/001_microcode.yml
  - ansible.builtin.import_tasks: subtasks/002_commonApps.yml
  - ansible.builtin.import_tasks: subtasks/003_autoRemove.yml
