- ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Enabling Contrib (Based)
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    backup: true
    search_string: deb http://deb.debian.org/debian/ bookworm main non-free
    line: deb http://deb.debian.org/debian/ bookworm main contrib non-free
    owner: root
    group: root
    mode: '0644'
  when: ansible_distribution == "Debian"

- name: Update all packages (Debian based)
  tags: always
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Importing RPM Fusion Free Key
  tags: always
  ansible.builtin.rpm_key:
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
    state: present
  when: ansible_os_family == "RedHat"

- name: Importing RPM Fusion Non-Free Key
  tags: always
  ansible.builtin.rpm_key:
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
    state: present
  when: ansible_os_family == "RedHat"

- name: Setting up RPM Fusion Free
  tags: always
  ansible.builtin.dnf:
    name: https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm
    state: present
  when: ansible_os_family == "RedHat"

- name: Setting up RPM Fusion Non-Free
  tags: always
  ansible.builtin.dnf:
    name: https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm
    state: present
  when: ansible_os_family == "RedHat"

- name: Update all packages (Fedora based)
  tags: always
  ansible.builtin.dnf:
    name: "*"
    update_cache: yes
    update_only: yes
    state: latest
  when: ansible_os_family == "RedHat"

- name: Copying Bash File
  tags: always
  ansible.builtin.copy:
    src: ../files/bashrc
    dest: /home/{{ invoking_user }}/.bashrc
    mode: "0660"
    owner: "{{ invoking_user }}"
    group: "{{ invoking_user }}"

- block:
  - ansible.builtin.import_tasks: subtasks/001_microcode.yml
  - ansible.builtin.import_tasks: subtasks/002_commonApps.yml
  - ansible.builtin.import_tasks: subtasks/003_autoRemove.yml
