- ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Enabling Contrib (Based)
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    backup: true
    search_string: deb http://deb.debian.org/debian/ bookworm main non-free
    line: deb http://deb.debian.org/debian/ bookworm main contrib non-free
    owner: root
    group: root
    mode: '0644'
  when: ansible_distribution == "Debian"

- name: Enabling RPM Fusion (Fedora Based)
  ansible.builtin.dnf:
    name: 'https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm'
    state: present
  when: ansible_distribution == "RedHat"

- name: Creating Mount Folder (jsproart)
  ansible.builtin.file:
    path: /mnt/NVME2
    state: directory
    owner: jpatr
    group: jpatr
    state: directory
  when: ansible_hostname == 'jsproart'

#- name: Mounting Second Drive (jsproart)
#  ansible.posix.mount:
#    src: /dev/nvme0n1p1
#    path: /mnt/NVME2
#    opts: 'defaults,x-gvfs-show 0 0'
#    fstype: btrfs
#    state: mounted
#  when: ansible_hostname == 'jsproart'

- name: Update all packages (Debian based)
  tags: always
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Update all packages (Fedora based)
  tags: always
  ansible.builtin.dnf:
    name: "*"
    update_only: yes
    update_cache: yes
    state: latest
  when: ansible_os_family == "RedHat"

- block:
  - ansible.builtin.import_tasks: subtasks/001_microcode.yml
  - ansible.builtin.import_tasks: subtasks/002_commonApps.yml
  - ansible.builtin.import_tasks: subtasks/003_autoRemove.yml
