- ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- block:
  tags: always
  - ansible.builtin.import_tasks: subtasks/001_microcode.yml
  - ansible.builtin.import_tasks: subtasks/002_commonApps.yml
  - ansible.builtin.import_tasks: subtasks/003_autoRemove.yml
