- ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Enabling Contrib (Based)
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    backup: true
    search_string: deb http://deb.debian.org/debian/ bookworm main non-free
    line: deb http://deb.debian.org/debian/ bookworm main contrib non-free
    owner: root
    group: root
    mode: '0644'
  when: ansible_distribution == "Debian"

- name: Installing RPM Fusion Free (Fedora Based)
  ansible.builtin.dnf:
    name: https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-42.noarch.rpm
    state: present
  when: ansible_distribution == "RedHat"

- name: Installing RPM Fusion Non-Free (Fedora Based)
  ansible.builtin.dnf:
    name: https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-42.noarch.rpm
    state: present
  when: ansible_distribution == "RedHat"

#- name: Importing (free) key
#  ansible.builtin.rpm_key:
#    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
#    state: present
#  when: ansible_distribution == "RedHat"

#- name: Importing (non-free) key
#  ansible.builtin.rpm_key:
#    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
#    state: present
#  when: ansible_distribution == "RedHat"

#- name: Enabling RPM Fusion (Fedora Based)
#  ansible.builtin.dnf:
#    name: 'https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm'
#    state: present
#  when: ansible_distribution == "RedHat"

#- name:  Enabling RPM Fusion - Non-Free (Fedora Based)
#  ansible.builtin.dnf:
#    name: 'https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm'
#    state: present
#  when: ansible_distribution == "RedHat"

#- name: Enable Fedora Cisco Openh264
#  community.general.dnf_config_manager:
#    name: fedora-cisco-openh264
#    state: enabled
#  when: ansible_distribution == "RedHat"

- name: Installing RPM Fusion AppStream Metadata
  ansible.builtin.dnf:
    name: pmfusion-\*-appstream-data
    state: present
  when: ansible_distribution == "RedHat"

- name: Update all packages (Debian based)
  tags: always
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Update all packages (Fedora based)
  tags: always
  ansible.builtin.dnf:
    name: "*"
    update_cache: yes
    update_only: yes
    state: latest
  when: ansible_os_family == "RedHat"

- name: Copying Bash File
  ansible.builtin.copy:
    src: ../files/bashrc
    dest: /home/{{ invoking_user }}/.bashrc
    mode: "0660"
    owner: "{{ invoking_user }}"
    group: "{{ invoking_user }}"

- name: Creating Mount Folder (jsproart)
  ansible.builtin.file:
    path: /mnt/NVME2
    state: directory
    owner: jpatr
    group: jpatr
    state: directory
  when: ansible_hostname == 'jsproart'

#- name: Mounting Second Drive (jsproart)
#  ansible.posix.mount:
#    src: /dev/nvme0n1p1
#    path: /mnt/NVME2
#    opts: 'defaults,x-gvfs-show 0 0'
#    fstype: btrfs
#    state: mounted
#  when: ansible_hostname == 'jsproart'

- block:
  - ansible.builtin.import_tasks: subtasks/001_microcode.yml
  - ansible.builtin.import_tasks: subtasks/002_commonApps.yml
  - ansible.builtin.import_tasks: subtasks/003_autoRemove.yml
