- ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- block:
  - ansible.builtin.import_tasks: subtasks/001-flatpak.yml
  - ansible.builtin.import_tasks: subtasks/002-apps.yml
  - ansible.builtin.import_tasks: subtasks/003-darkMode.yml
  - ansible.builtin.import_tasks: subtasks/005-drawIO.yml
  - ansible.builtin.import_tasks: subtasks/006-kvm.yml
  - ansible.builtin.import_tasks: subtasks/007-theia.yml
  - ansible.builtin.import_tasks: subtasks/008-steam.yml
  - ansible.builtin.import_tasks: subtasks/009-libreoffice.yml
  - ansible.builtin.import_tasks: subtasks/010-flatApps.yml
  - ansible.builtin.import_tasks: subtasks/011-docker.yml
#  - ansible.builtin.import_tasks: subtasks/004-angryIpScanner.yml
#  - ansible.builtin.import_tasks: subtasks/012-makeMKV.yml
