- name: Installing NVidia Drivers and Hardware Codecs
  ansible.builtin.dnf:
    name:
      - mesa-va-drivers
      - mesa-va-drivers-freeworld
      - akmod-nvidia
      - radeontop
      - vulkan
  when: ansible_facts['os_family'] == "RedHat"

#- name: Enabling ASUS-Linux Repo
#  ansible.builtin.command:
#    cmd: dnf copr -y enable lukenukem/asus-linux
#  when: ansible_facts['os_family'] == "RedHat"

- name: Update all packages (Fedora based)
  tags: always
  ansible.builtin.dnf:
    name: "*"
    update_cache: yes
    update_only: yes
    state: latest
  when: ansible_facts['os_family'] == "RedHat"

#- name: Install asusctl and supergfxctl
#  ansible.builtin.dnf:
#    name:
#      - asusctl
#      - supergfxctl
#      - asusctl-rog-gui
#  when: ansible_facts['os_family'] == "RedHat"

#- name: Enabling ASUS Service
#  ansible.builtin.systemd_service:
#    name: asusd
#    enabled: true
#  when: ansible_facts['os_family'] == "RedHat"

#- name: Enabling Supergfxctl Service
#  ansible.builtin.systemd_service:
#    name: supergfxd
#    enabled: true
#  when: ansible_facts['os_family'] == "RedHat"

- name: Creating Mount Folder (jsproart)
  ansible.builtin.file:
    path: /mnt/Gaming
    state: directory
    owner: jpatr
    group: jpatr
    mode: "0770"

- name: Mounting Second Drive (jsproart)
  ansible.posix.mount:
    src: /dev/nvme1n1p5
    path: /mnt/Gaming
    opts: 'defaults,x-gvfs-show 0 0'
    fstype: btrfs
    boot: true
    state: present
