- name: Installing NVidia Drivers and Hardware Codecs
  ansible.builtin.dnf:
    name:
      - kernel-devel
      - mesa-va-drivers
      - mesa-va-drivers-freeworld
      - akmod-nvidia xorg-x11-drv-nvidia-cuda
      - nvtop
      - radeontop
  when: ansible_os_family == "RedHat"

- name: Enabling NVidia Hibernate Service
  ansible.builtin.systemd_service:
    name: nvidia-hibernate.service
    enabled: true
  when: ansible_os_family == "RedHat"

- name: Enabling NVidia Suspend Service
  ansible.builtin.systemd_service:
    name: nvidia-suspend.service
    enabled: true
  when: ansible_os_family == "RedHat"

- name: Enabling NVidia Resume Service
  ansible.builtin.systemd_service:
    name: nvidia-resume.service
    enabled: true
  when: ansible_os_family == "RedHat"

- name: Enabling NVidia Power Service
  ansible.builtin.systemd_service:
    name: nvidia-powerd.service
    enabled: true
  when: ansible_os_family == "RedHat"

- name: Enabling ASUS-Linux Repo
  ansible.builtin.command:
    cmd: dnf copr enable lukenukem/asus-linux
  when: ansible_os_family == "RedHat"

- name: Update all packages (Fedora based)
  tags: always
  ansible.builtin.dnf:
    name: "*"
    update_cache: yes
    update_only: yes
    state: latest
  when: ansible_os_family == "RedHat"

- name: Install asusctl and supergfxctl
  ansible.builtin.dnf:
    name:
      - asusctl
      - supergfxctl
      - asusctl-rog-gui
  when: ansible_os_family == "RedHat"

- name: Enabling ASUS Service
  ansible.builtin.systemd_service:
    name: asusd
    enabled: true
  when: ansible_os_family == "RedHat"

- name: Enabling Supergfxctl Service
  ansible.builtin.systemd_service:
    name: supergfxd
    enabled: true
  when: ansible_os_family == "RedHat"

- name: Creating Mount Folder (jsproart)
  ansible.builtin.file:
    path: /mnt/NVME2
    state: directory
    owner: jpatr
    group: jpatr
    mode: "0770"
    state: directory

- name: Mounting Second Drive (jsproart)
  ansible.posix.mount:
    src: /dev/nvme0n1p1
    path: /mnt/NVME2
    opts: 'defaults,x-gvfs-show 0 0'
    fstype: btrfs
    state: mounted

