- name: Create First Run file.
  ansible.builtin.file:
    path:  /home/{{ invoking_user }}/.firstRun
    state: touch
    mode: '0777'

- name: Rebooting
  ansible.builtin.command: reboot
  become: yes
