- name: Create First Run file.
  ansible.builtin.file:
    path: /home/{{ invoking_user }}/.firstRun
    state: touch
    mode: '0777'

# Gemma on LM-Studio helped me correct this line
- name: Check if Reboot is Needed
  ansible.builtin.needs_reboot:
    check_restart: true
  register: reboot_check

- name: Rebooting (Conditional)
  ansible.builtin.command: reboot
  become: true
  when: reboot_check.reboot
